# yaml-language-server: $schema=
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "grafana-mcp.fullname" . }}-pdb
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "grafana-mcp.selectorLabels" . | nindent 6 }}
{{- end }}