# yaml-language-server: $schema=
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-mcp.fullname" . }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "grafana-mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP